### ISSUE TITLE
allow multiple +ve & -ve example sets

### ISSUE THREAD

**Issue by crislin2046** [crislin2046/selector-generalization#12]
This means multiple positive sets and 
multiple negative sets

So a single "selector" or "pattern" or "locator" 
Can incorporate multiple positive and negative sets

**Comment by dosyago-coder-0** [comment]
Composition ought to have:

- way to 'open' a set so you can add examples to it (+ve and -ve)
- way to 'make' new set you can add examples to it
- different colors? for different sets in the group. 
- good names: maybe these subsets ought to be called patterns or patches.
- decisions: can we add negative examples to subsets, or only to the whole group? or to both?
- what does the UI look like for this (in the tester, anyway)?
- decided: i definitely think we can add negative examples to both subset and whole group, just seems to give more control and be easier to reason about if both are provided since each appears to have appropriateness for different intents
- can we arbitrarily nest subsets ? hmmm....possibly confusing and weird UI. I'm thinking maybe not. Tho if we did a 'sort-of' version of this by including a set as a subset by reference ( so they have names / ids ), maybe that's ok.
